version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    executor:
      name: node/default
      tag: '16.13'
    steps:
      - checkout
      - run: yarn install
      - run: CI=false yarn run build
      - run: CI=false yarn run build-standalone-worker
      - run: sudo yarn global add aws-cdk@1.80.0
      - run: CI="" cd deployment && yarn install && yarn build
      - run: cd deployment && cdk bootstrap && cdk deploy --progress events --ci --require-approval never
workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
