apiVersion: apps/v1
kind: Deployment
metadata:
  name: motivus-worker
  namespace: worker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: motivus-worker
  template:
    metadata:
      labels:
        app: motivus-worker
    spec:
      containers:
        - image: southamerica-west1-docker.pkg.dev/motivus-257216/motivus-repo/worker
          imagePullPolicy: Always
          name: worker
          env:
            - name: WB_WORKER_TOKEN
              value: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJtb3RpdnVzX3diX2FwaSIsImV4cCI6MjYwNjE1NDYyOCwiaWF0IjoxNjYwMDc0NjI4LCJpc3MiOiJtb3RpdnVzX3diX2FwaSIsImp0aSI6ImMxYTJmNjI4LTY0MDEtNDQxYi04YjhiLWFjNDY2MzExNGNhNCIsIm5iZiI6MTY2MDA3NDYyNywic3ViIjoiMSIsInR5cCI6ImFjY2VzcyJ9.MOnjIQvc5djf3wALjw9pkTYqof92MpSNBFMJyTt9CDon97TrWpf08zaHFu2b07DY8kp_NGOq8VDrWGzIsKFyLQ
            - name: PROCESSING_THREADS
              value: "2"
          resources:
            limits:
              cpu: "4"
              memory: 4Gi
            requests:
              cpu: "4"
              memory: 4Gi
      terminationGracePeriodSeconds: 25
