apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: wb-custom-metric
  name: wb-custom-metric
  namespace: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      run: wb-custom-metric
  template:
    metadata:
      labels:
        run: wb-custom-metric
    spec:
      containers:
      # metrics to Stackdriver
      - name: prometheus-to-sd
        image: gcr.io/google-containers/prometheus-to-sd:v0.5.0
        command: ["/monitor"]
        args:
        - --source=:https://waterbear.api.motivus.cl/metrics
        - --stackdriver-prefix=custom.googleapis.com
        - --pod-id=$(POD_ID)
        - --namespace-id=$(POD_NAMESPACE)
        env:
        # save Kubernetes metadata as environment variables for use in metrics
        - name: POD_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
